app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, current_user 
from . import login_manager
from flask_admin.contrib.sqla import ModelView
from datetime import datetime
from flask import session, abort


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255), index=True)
    bio = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    comment = db.relationship('Comments', backref='user', lazy='dynamic')
    post = db.relationship('Posts', backref='user', lazy='dynamic')
 
    
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save_user(self):
        '''
        Function to save a user
        '''
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"'{self.username}'"

    

class Posts(db.Model):
    '''
    Model class/db table for the post made by the writer
    Args:
        db.Model: Connect our class to the database
    '''
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200))
    author = db.Column(db.String(100))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)
    post = db.Column(db.Text())
    comments = db.relationship('Comments', backref='comment', lazy='dynamic')
    views = db.Column(db.Integer, default=0)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    

    

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"Post '{self.post}', '{self.date_posted}'"

class Comments(db.Model):
    __tablename__ = 'comments' 
    
    id = db.Column(db.Integer, primary_key = True)
    comments = db.Column(db.Text(),nullable=False)
    title = db.Column(db.String(),nullable=False)
    post_id = db.Column(db.Integer,db.ForeignKey('posts.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
        
    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()
        
    @classmethod
    def get_comments(cls,posts_id):
        comments = Comments.query.filter_by(posts_id=posts_id).all()

        return comments
        
    def __repr__(self):
        return f'Comment{self.comments}'
    
    
class Subscribe(db.Model):
    __tablename__='subscribers'

    id =db.Column(db.Integer,primary_key=True)
    email=db.Column(db.String(255),unique=True)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

    def delete_subscriber(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Subscribe {self.email}"



class Quote:
    """
    class to define Quote Objects
    """
    def __init__(self,quote,author):
        self.quote = quote
        self.author = author

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, PasswordField, SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
    

class BlogForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    post = TextAreaField('Blog', validators=[Required()])
    submit = SubmitField('Post Blog')

    
class CommentsForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from config import config_option
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_admin.contrib.sqla import ModelView


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES )
mail = Mail()


def create_app(config_name):
    
    # Initializing the application
    app = Flask(__name__)
    
    # Creating the app configurations
    app.config.from_object(config_option[config_name])
    
    # Initializing our extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    # Will add the views and forms
    from app.models import Posts,User,Comments
    
    # Configure uploadset
    configure_uploads(app, photos)
    
    # Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors, forms

app/main/views.py
from flask import render_template, redirect, url_for,abort,request,flash
from . import main
from flask_login import login_required, current_user
from .forms import UpdateProfile, BlogForm
from .. import db, photos
from ..models import User, Posts, Comments
from ..requests import get_quotes


@main.route('/')
@main.route('/Home')
def index():
    quote = get_quotes()
    title = "Home - Welcome to Bloggers."
    return render_template('index.html', title=title, quote=quote)


@main.route('/blogs')
def blogs():
    posts = Posts.query.all()
    title = "Blogs - Welcome to Bloggers."
    return render_template('blogs.html', posts = posts, title=title)

@main.route('/add_blog', methods=["GET","POST"])
@login_required
def add_blog():
    form = BlogForm()
    
    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data
        user = current_user._get_current_object().id
        new_blog_object = Posts(user_id=user, title=title, post=post)
        new_blog_object.save_post()
        return redirect(url_for('main.blogs'))
    
    title = "Add Blog - Welcome to Bloggers."
    return render_template('add_blog.html', title=title, blog_form=form)

    
@main.route('/user/<uname>')
def profile(uname):
    title = "Profile - Welcome to Bloggers."
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user, title=title)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    title = "Update Profile - Welcome to Bloggers."
    
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form, title=title)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/comments/<int:posts_id>', methods=['GET','POST'])
@login_required
def new_comment(posts_id):
    title = "Comment - Welcome to Bloggers."
    form = CommentsForm()
    posts = Posts.query.get(posts_id)
    comment = Comments.query.filter_by(post_id=posts_id).all()
    if form.validate_on_submit():
        comments = form.comment.data
        
        post_id = posts_id
        user_id = current_user._get_current_object().id
        new_comment= Comments(comments=comments,posts_id=post_id, user_id=user_id)
        new_comment.save_comment()      
       
        return redirect(url_for('main.new_comment', posts_id=post_id))
    
    return render_template('comments.html', form=form, comment=comment, posts_id=post_id,posts=posts, title=title)

app/templates/add_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-8 pitch-form">
            <h2>Create Blog</h2>
            {{wtf.quick_form(blog_form)}}
        </div>
    </div>
</div>

{% endblock%}

app/templates/base.html
<script src="https://kit.fontawesome.com/cc1a8ab208.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="../static/css/style.css">
{% extends 'bootstrap/base.html' %}

<!-- Navbar block -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

<!-- Content block -->
{% block content %}

{% endblock %}

app/templates/blogs.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="blog-posts">
            {{ macro.displayBlog(posts)}}
        </div>
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <img src="../static/images/nYgy58eb9aw (2).jpg" alt="" style="background: cover;">
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr>
            <blockquote class="blockquote text-center">
                <p class="mb-0">{{quote.quote}}</p>
                <footer class="blockquote-footer"><cite>{{quote.author}}</cite></footer>
              </blockquote>
        </div>
    </div>
    
    <div class="row mt-5">
        <hr>
        <div class="col-md-12">
            <h1 class="text-info fw-bolder">
                <i>About Bloggers</i>
            </h1>
        </div>
        <div class="col-md-12">
            <h3>Bloggers is a site where users are able to post and view other people's blogs.The site is a community
                that connects all people together without any form of discrimination. Have a chance to see all kinds of
                news around.
            </h3>
            {% if current_user.is_authenticated %}
            <h4>Let others know what you are thinking <a href="{{url_for('main.add_blog')}}">Add Blog</a></p>
            {% else %}
            <h4>Join us today <a href="{{url_for('auth.login')}}">Sign In</a> and have a chance to post your blogs on our site</p>
            {% endif %}
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <hr>
            <footer>
                <p style="text-align: center"> Copyright &copy;
                    <script>document.write(new Date().getFullYear())</script> Portfolio All Rights Reserved
                </p>
            </footer>
        </div>
    </div>
</div>

{% endblock %}

app/templates/macros.html
{% macro displayBlog(posts) %}
{% for post in posts %}
<div class="col-md-4">
    <div class="panel">
        <div class="panel-header bg-info">
            <h2>{{post.title}}</h2>
        </div>
        <div class="panel-body">
            <h3>{{post.post}}</h3>
            <p>Posted by: <span><b>{{ post.user }}</b></span></a> on <i>{{post.date_posted.strftime('%B %d, %Y')}}</i></p>
            <p>{{post.comments.count()}} Comments</p>
        </div>
        <div class="panel-footer">
            <a href="">Add comment</a>
        </div>
    </div>
</div>
{% else %}
<div class="row">
    <div class="col-md-12">
        <h1>There are no posts at the moment</h1>
    </div>
</div>
</div>
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{url_for('main.index')}}"><i class="fas fa-blog"></i></a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{{url_for('main.index')}}">Home<span class="sr-only">(current)</span></a></li>
          <li><a href="{{url_for('main.blogs')}}">Blogs</a></li>
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.add_blog')}}">Add Blog</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
          {%endif%}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}

        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>

            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}